[default]
duration = "2hours"
mode = "stretch"
sorting = "random"

[any]
path = "/home/sourav/Downloads/revo/image"
exec = "/home/sourav/.config/wpaperd/scripts.d/echo.sh"

#[default.transition.hexagonalize]
## default values for hexagonalize
## steps = 50
## horizontal-hexagons = 20.0
